### ISSUE TITLE
Incorrect capture of images in Markdown mode

### ISSUE THREAD

**Issue by bvernay** [haesleinhuepf/imagejmacromarkdown#1]
Hi Robert,

I ran first_test.ijmmd and the processed images are not properly captured in the html file. See attached files.

Bertrand

<img width="243" alt="Capture" src="https://user-images.githubusercontent.com/18054291/77536650-f30eac00-6e9c-11ea-90c3-a1756c41d323.PNG">

*******************************************
Bertrand Vernay, PhD
Head of the Photonic Microscopy Facility
http://quest.igbmc.fr/
http://www.igbmc.fr/technologies/5/team/55/
https://github.com/bvernay

Office:+33 (0)3 69 48 51 27
Office: CBI, E1005
ORCID 0000-0002-7843-3872
IGBMC - CNRS UMR 7104 - Inserm U 1258
1 rue Laurent Fries
BP 10142
67404 Illkirch CEDEX
France Tél +33 (0)3 88 65 32 00
Fax +33 (0)3 88 65 32 01

**Comment by haesleinhuepf** [comment]
Hey @bvernay 

thanks for the bug report! You are using Linux, right?

Cheers,
Robert

**Comment by bvernay** [comment]
windows 10. I can try on my linux machine


Cordialement,


Bertrand


********************************************
Bertrand Vernay, PhD
Head of the Photonic Microscopy Facility
http://quest.igbmc.fr/
http://www.igbmc.fr/technologies/5/team/55/
https://github.com/bvernay

Office:+33 (0)3 69 48 51 27

Office: CBI, E1005

ORCID 0000-0002-7843-3872

IGBMC - CNRS UMR 7104 - Inserm U 1258
1 rue Laurent Fries
BP 10142
67404 Illkirch CEDEX
France Tél +33 (0)3 88 65 32 00
Fax +33 (0)3 88 65 32 01
________________________________
De : Robert Haase <notifications@github.com>
Envoyé : mercredi 25 mars 2020 13:44:16
À : haesleinhuepf/imagejmacromarkdown
Cc : Bertrand VERNAY; Mention
Objet : Re: [haesleinhuepf/imagejmacromarkdown] Incorrect capture of images in Markdown mode (#1)


Hey @bvernay<https://github.com/bvernay>

thanks for the bug report! You are using Linux, right?

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Het @bvernay,

I also developed it on Windows. Just wondering what's different. Do you have multiple screens attached?
