### ISSUE TITLE
No markdown file appearing (Log box empty) when running code using IJ1 Macro Markdown language

### ISSUE THREAD

**Issue by CiaraShortiss** [haesleinhuepf/imagejmacromarkdown#2]
Hi Robert,

Thanks for sharing your fantastic YouTube series on BioImage analysis and ImageJ. The most thorough and well explained I've found by far. Very grateful to have them to learn from, so thank you! 

I have not been able to get your Macro Mackdown update to work recently. It was working correctly until just a few days ago, and now (even though I have changed nothing) is not producing markdown files anymore. The log box appears as empty when I hit run on a script that is written with the IJ1 Macro Markdown Language. A few others who have downloaded the update are also having this issue. I have uninstalled and re-installed the update with no success. Sorry I  can't be more descriptive than that. It all looks correct (to me) but is not working.

Thanks in advance for your time, 

Ciara

**Comment by haesleinhuepf** [comment]
It's fixed with the 0.3.4 release. Thanks for reporting! 🤩
